name: sc2
version: 0.1.0
synopsis: an interface to the Starcraft II bot API
maintainer: Aaron Griffith <aargri@gmail.com>
license: MIT
#github: agrif/sc2
category: Network
extra-source-files:
#  - README.md

dependencies:
  - base >= 4.7 && < 5
  - proto-lens >= 0.2 && < 0.3
  - proto-lens-protoc >= 0.2 && < 0.3
  - lens-family >= 1.2 && < 2
  - data-default-class >= 0.1 && < 0.2
  - optparse-applicative >= 0.13 && < 0.14
  - process >= 1.4 && < 2
  - websockets >= 0.10 && < 0.11
  - network >= 2.6 && < 3
  - freer-effects >= 0.3 && < 0.4
  - containers >= 0.5 && < 0.6
  - text >= 1.2 && < 2
  - directory >= 1.3 && < 2
  - bytestring >= 0.10 && < 0.11
  - sc2-proto

library:
  source-dirs: src

executables:
  sc2-demo:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - sc2
